### ISSUE TITLE
Checker crash

### ISSUE THREAD

**Issue by hsimonis** [renault-iaa/challenge-roadef-2022#49]
Dear organizers,

I get the following crash of the checker on some results produced for instance AS (and other instances).
C:\Users\hsimonis\Documents\projects\Roadef2022\checker>java -Xmx4g -DLOG_FILENAME="logs/logchecker" -Dlogback.configurationFile=logback.xml -jar ./CheckerChallenge-1.10.0.jar checkerC-AS.csv
2023-03-16 12:00:35.866 [main    ] INFO  - read file of instances
2023-03-16 12:00:35.871 [main    ] INFO  - Read of instances file : 1 instances
2023-03-16 12:00:35.872 [main    ] INFO  - read instance AS
2023-03-16 12:00:35.872 [main    ] INFO  - read parameters file ../import/datasetC/AS/input_parameters.csv
2023-03-16 12:00:35.873 [main    ] INFO  - Read of parameters file
2023-03-16 12:00:35.873 [main    ] INFO  - read input items file ../import/datasetC/AS/input_items.csv
2023-03-16 12:00:36.185 [main    ] INFO  - Read of input items file : 15867 items
2023-03-16 12:00:36.185 [main    ] INFO  - read input trucks file ../import/datasetC/AS/input_trucks.csv
2023-03-16 12:00:36.488 [main    ] INFO  - Read of input trucks file : 1593 planned trucks
2023-03-16 12:00:36.489 [main    ] INFO  - read output trucks file data/datasetC/AS/output_trucks.csv
2023-03-16 12:00:36.510 [main    ] INFO  - Read of output trucks file : 1797 trucks
2023-03-16 12:00:36.510 [main    ] INFO  - read output stacks file data/datasetC/AS/output_stacks.csv
2023-03-16 12:00:36.594 [main    ] INFO  - Read of output stacks file : 19585 stacks
2023-03-16 12:00:36.594 [main    ] INFO  - read output items file data/datasetC/AS/output_items.csv
2023-03-16 12:00:36.614 [main    ] ERROR - Crash !!
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
        at model.InputTruck.getPlantDockLoadingOrder(InputTruck.java:286)
        at model.OutputStack.addItem(OutputStack.java:44)
        at model.OutputItem.setOutputStack(OutputItem.java:167)
        at io.OutputItemsReader.readFile(OutputItemsReader.java:97)
        at main.Main.checkInstancesWriteLocalReport(Main.java:185)
        at main.Main.main(Main.java:59)
2023-03-16 12:00:36.614 [main    ] ERROR - model.InputTruck.getPlantDockLoadingOrder(InputTruck.java:286)
2023-03-16 12:00:36.614 [main    ] ERROR - model.OutputStack.addItem(OutputStack.java:44)
2023-03-16 12:00:36.615 [main    ] ERROR - model.OutputItem.setOutputStack(OutputItem.java:167)
2023-03-16 12:00:36.615 [main    ] ERROR - io.OutputItemsReader.readFile(OutputItemsReader.java:97)
2023-03-16 12:00:36.615 [main    ] ERROR - main.Main.checkInstancesWriteLocalReport(Main.java:185)
2023-03-16 12:00:36.615 [main    ] ERROR - main.Main.main(Main.java:59)

 It is highly likely that the results tested are not a legal solution, are you still interested in fixing this problem in the checker to improve stability? Files available on request.

Best regards

Helmut

**Comment by renault-iaa** [comment]
Hello @hsimonis,

Yes we want to fix the crash of the checker, it should never happen whatever the solution files. Can you send us your result files ?

Thanks
Alain

Email : alain.nguyen@renault.com

**Comment by renault-iaa** [comment]
Hello @hsimonis,

A new version of the checker has been published, which corrects the crash issue.

Best regards
Alain
